# Generated by Django 2.1.3 on 2018-11-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmitProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('text', models.CharField(max_length=50, verbose_name='Message')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'verbose_name': 'KYC Submit',
                'verbose_name_plural': 'KYC Submit',
            },
            bases=('viewflow.process',),
        ),
    ]
