# Generated by Django 2.1.3 on 2018-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_flow', '0002_auto_20181128_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsubmitprocess',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
    ]
